server:
  port: 8083
  servlet:
    context-path: /monitor
Spring:
  security: #Spring Security安全框架
    user: #若要访问端点信息，需要配置用户名和密码
      name: issgang
      password: 123456
      roles: admin
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8084
    servlet:
      context-path: /monitor1
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'